version: '3.9'

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP finto
      - "8025:8025"   # Interfaccia web per vedere le email

  backend:
    image: maven:3.9-eclipse-temurin-21
    container_name: bugboard-backend
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      # ðŸ‘‰ DATABASE RENDER
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d4g9bhe3jp1c73dgg2t0-a.frankfurt-postgres.render.com:5432/bugboard26
      SPRING_DATASOURCE_USERNAME: bugboard26_user
      SPRING_DATASOURCE_PASSWORD: RKOQcH7jpcIr01Clz7nGZFCvQE45Z2xC

      # ðŸ‘‰ Config SMTP per MailHog
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME:
      SPRING_MAIL_PASSWORD:
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: false
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: false

      # Profilo Spring (opzionale)
      SPRING_PROFILES_ACTIVE: dev

    depends_on:
      - mailhog
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - maven-cache:/root/.m2

volumes:
  maven-cache:
